### ISSUE TITLE
Problems with query string

### ISSUE THREAD

**Issue by ratthing2** [prologic/gopherproxy#1]
1. Go to the URL above.
2. Click on "Search Veronica-2"  This will submit the query to Cameron
Kaiser's Veronica search engine.
3. For the query, do a search on the term "bash".
4. On the first results page, scroll down then click on the link "Next
30 Matches"
5. You get an error, "Sorry, no valid keywords in your query".  Note
that this link works correctly with regular gopher clients.

I believe the proxy is replacing the single space (%20) in the query
string with a plus sign (+), which of course is not unusual, but the
buckd/Veronica combination at floodgap doesn't understand it.  i'm not a
Go programmer so I didn't take the time to peruse the code.

**Comment by prologic** [comment]
Thank you for reporting this! I'm already working on a fix and will have a
PR shortly.


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by prologic** [comment]
The latest series of commits to go-gopher and gopherproxy should fix this
issue.

Please rebuild and let me know!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by ratthing2** [comment]
James, for some reason now I am getting an error on build.  Using version 1.7.4 of go on a CentOS 6 linux server.

GOPATH=/root/.go
GOROOT=/usr/lib/golang
Prologic source files are in /root/.go/src/prologic/go-gopher /root/.go/src/prologic/gopherproxy

# net
/usr/lib/golang/src/net/rawconn.go:28: c.fd.pfd undefined (type *netFD has no field or method pfd)
/usr/lib/golang/src/net/rawconn.go:40: c.fd.pfd undefined (type *netFD has no field or method pfd)
/usr/lib/golang/src/net/rawconn.go:52: c.fd.pfd undefined (type *netFD has no field or method pfd)
/usr/lib/golang/src/net/writev_unix.go:14: undefined: Buffers
/usr/lib/golang/src/net/writev_unix.go:25: undefined: Buffers
/usr/lib/golang/src/net/writev_unix.go:26: fd.pfd undefined (type *netFD has no field or method pfd)

I've been unable to find any info on this error.  Any ideas?

**Comment by prologic** [comment]
Wow! That's super weird.

What does Google say about this build error?

I build/test on very recent Go compilers 1.8 something on OS X

But I can build/release re-release binaries if that helps you test the
recent changes?


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by ratthing2** [comment]
I went ahead and deleted the Go packages from my server and installed the latest version manually, and everything worked!  The bug is also squashed!

**Comment by prologic** [comment]
Lovely (y)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
