### ISSUE TITLE
Page not rendering correctly

### ISSUE THREAD

**Issue by ratthing2** [prologic/gopherproxy#2]
Go to the following URL:

http://ratthing.com:7780/pollett.org/1

That page looks OK when I view it in a gopher client.

Looking at the gophermap file (attached to this email) it looks like he
has put fake selector, host, and port strings on the "i" lines.  That
may be throwing off your gophermap parsing.

**Comment by prologic** [comment]
Thanks for reporting this! Do you want to have a crack at fixing this one?
I think as you suggest this may just be an incorrect assumption I'm making
in the parser.


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by ratthing2** [comment]
Hi James, I'm not a Go developer but I'll be glad to have a look.

**Comment by prologic** [comment]
Ahh no worries :D I'm going to try to address both in any case; I'll update
my progress on both issues!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by ratthing2** [comment]
Hi James,  I did a bit of investigating and discovered the problem is weirder than I thought.  I don't think it is the fault of your software.

Whenever I curl download a copy of the gophermap/index file from pollett.org, and put it on my own gopher server (Motsognir), it works just fine through your gopherproxy.  See

http://ratthing.com:7780/ratthing.com/1/~rlopez/test

But when I point to the file with gopherproxy, it is improperly rendered.

THe only thing I could see in the gophermap file are some extra ^M characters at the start of all the lines except for line 1.

Interestingly, it is line 1 that is the only line that is rendered correctly by gopherproxy.  I should also note that the pollett.org does NOT render correctly using version 3.09 of the old gopher CLI program.  

Pollett.org is using a php-based gopher server ("atto") that he wrote himself.  

https://github.com/cpollett/atto

My guess is that there is some odd encoding coming out of that server that is causing problems for both the old CLI gopher program and gopherproxy.

I would mark this issue as "closed".  This is the only site where I encountered this error, and it was with a new gopher server framework.

**Comment by prologic** [comment]
But this could still mean I'm parsing the client response (gopher)
incorrectly?

i.e: assuming \n ending (but getting \r\n)?


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by prologic** [comment]
Upon further investigation; yes you are right. atto or the gophermap in question is quite broken :/

**Comment by prologic** [comment]
Fix in https://github.com/prologic/go-gopher/commit/435112fefe7986076b3fc2dd6718a5cc2f68dbbd

**Comment by ratthing2** [comment]
bug is fixed

**Comment by prologic** [comment]
Lovely (y)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
