### ISSUE TITLE
Blocking web crawlers or supporting Robots?

### ISSUE THREAD

**Issue by prologic** [prologic/gopherproxy#6]
/cc @ratthing2 -- Let's discuss this as per #5

**Comment by jamestomasino** [comment]
Perhaps you can intercept the requested path in the Handler function and scrub it against a preset list of exclusions (for a block list) and special files (for the robots.txt handling)? I'd take a stab at it, but I'm not very familiar with Go.

**Comment by prologic** [comment]
Is it enough just to implement a `/robots.txt` route?

**Comment by jamestomasino** [comment]
This issue (#6) would be fine with just a robots.txt route. To also fix #7, handling specific routes by way of an external block list file would probably do it. I don't think you'd want the specific blocks built into source, but read from a config file somewhere so you could modify it as bad actors appear.

**Comment by prologic** [comment]
Agreed. So This should just be about implementing `/robots.txt` and possibly configuring it.
